### ISSUE TITLE
Automatically add reviewers when certain part of the code changes

### ISSUE THREAD

**Issue by briacp** [omegat-org/omegat#696]
> It would be better if modifications that impact Bundle.properties could automatically trigger a UI review and a documentation ticket.

_Originally posted by @brandelune in https://github.com/omegat-org/omegat/issues/675#issuecomment-1627602631_

---

This can be done by adding a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) in the `.github` directory.

This way, if a PR modifies `Bundle.properties`, Philippe is automatically asked to review the PR.

**Comment by Kazephil** [comment]
That's pretty neat.

Now we just have to hope people are patient when "real life" gets in the way and it takes me a few days to have a chance to look at the PR!
