### ISSUE TITLE
Team projects don't save/sync additional glossary files

### ISSUE THREAD

**Issue by MarioLiebisch** [omegat-org/omegat#708]
Currently running OmegaT 6.0.0(1bf1729c) with a team project I've noticed OmegaT will only sync whatever glossary file is specifically named in the project settings (`glossary/glossary.txt` by default), while still all existing files are actually parsed and used.

I think there should be an option to store all glossary files (minus the backups, obviously) with the team project or to prevent data loss at least potentially a short readme file added by default (same for other similar directories that aren't synced, like `tm`).

This file could be as simple as:

```
All txt/utf8 files in this directory are used by OmegaT to generate an online glossary.
If this is a team project, only the contents of the primary glossary file (see project settings) are synced.
```

**Comment by miurahr** [comment]
Please post to genuine bug tracker.
https://sourceforge.net/p/omegat/bugs/
